services:
  # Zookeeper - control kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"

  # Kafka - data pipeline with validation
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    env_file: ".env"

  # PostgreSQL - transaction logs, app traces
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ".env"

  # MongoDB - account/user data
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file: ".env"