services:
  # Zookeeper - control kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    env_file: ".env"

  # Kafka - data pipeline with validation
  kafka:
    image: confluentinc/cp-kafka:latest
    env_file: ".env"
    depends_on:
      - zookeeper

  # Postgres - transaction logs, app traces
  postgres:
    image: postgres:latest
    env_file: ".env"
    ports:
      - "5432:5432"

  # Mongo - account/user data
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  # Express API - backend services
  backend:
    build:
      context: ../node
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      #- kafka - put back when kafka set up
      - postgres
      - mongo

  # Next.js - frontend application
  frontend:
    build:
      context: ../node
      dockerfile: ../node/Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - backend