services:
  # Kafka - data event queue with validation
  kafka:
    image: bitnami/kafka:latest
    env_file: ".env"
    ports:
      - "9092:9092"

  # Postgres - integration logs
  postgres:
    image: postgres:latest
    env_file: ".env"
    ports:
      - "5432:5432"

  # Mongo - account/user data
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  # Express API - backend services
  backend:
    build:
      context: ../node
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - kafka
      - postgres
      - mongo

  # Next.js - frontend & request proxy
  frontend:
    build:
      context: ../node
      dockerfile: ../node/Dockerfile.frontend

    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - backend